<<<<<<< HEAD
# cloudbuild.yaml
steps:
  # 1) Obtener el secreto cookies.json y volcarlo en el contenedor
  - name: gcr.io/cloud-builders/gcloud
    id: 'fetch-cookies'
    entrypoint: bash
    args:
      - -c
      - |
        mkdir -p backend
        gcloud secrets versions access latest \
          --secret="cookies-json" > backend/cookies.json

  # 2) Construir la imagen Docker
  - name: gcr.io/cloud-builders/docker
    id: 'docker-build'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/malligasta:$SHORT_SHA',
        '.'
      ]

  # 3) Push de la imagen a Container Registry
  - name: gcr.io/cloud-builders/docker
    id: 'docker-push'
    args:
      [
        'push',
        'gcr.io/$PROJECT_ID/malligasta:$SHORT_SHA'
      ]

  # 4) Desplegar en Cloud Run
  - name: gcr.io/cloud-builders/gcloud
    id: 'deploy-cloud-run'
    args:
      [
        'run',
        'deploy',
        'malligasta-service',
        '--image',
        'gcr.io/$PROJECT_ID/malligasta:$SHORT_SHA',
        '--region',
        'us-central1',            # elige tu región
        '--platform',
        'managed',
        '--allow-unauthenticated',
        '--port',
        '8080',
        # Define variables de entorno si las necesitas:
        '--set-env-vars',
        'CSV_PATH=/app/backend/datos_turisticos.csv'
      ]

images:
  - 'gcr.io/$PROJECT_ID/malligasta:$SHORT_SHA'
=======
# cloudbuild.yaml
steps:
  # 1) Obtener el secreto cookies.json y volcarlo en el contenedor
  - name: gcr.io/cloud-builders/gcloud
    id: 'fetch-cookies'
    entrypoint: bash
    args:
      - -c
      - |
        mkdir -p backend
        gcloud secrets versions access latest \
          --secret="cookies-json" > backend/cookies.json

  # 2) Construir la imagen Docker
  - name: gcr.io/cloud-builders/docker
    id: 'docker-build'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/malligasta:$SHORT_SHA',
        '.'
      ]

  # 3) Push de la imagen a Container Registry
  - name: gcr.io/cloud-builders/docker
    id: 'docker-push'
    args:
      [
        'push',
        'gcr.io/$PROJECT_ID/malligasta:$SHORT_SHA'
      ]

  # 4) Desplegar en Cloud Run
  - name: gcr.io/cloud-builders/gcloud
    id: 'deploy-cloud-run'
    args:
      [
        'run',
        'deploy',
        'malligasta-service',
        '--image',
        'gcr.io/$PROJECT_ID/malligasta:$SHORT_SHA',
        '--region',
        'us-central1',            # elige tu región
        '--platform',
        'managed',
        '--allow-unauthenticated',
        '--port',
        '8080',
        # Define variables de entorno si las necesitas:
        '--set-env-vars',
        'CSV_PATH=/app/backend/datos_turisticos.csv'
      ]

images:
  - 'gcr.io/$PROJECT_ID/malligasta:$SHORT_SHA'
>>>>>>> e707900abc7e99db73049c63d590af7cb1a84006
timeout: '1200s'